### ISSUE TITLE
Request: Addition

### ISSUE THREAD

**Issue by ForceGT** [saifshaikh1805/tata-sky-m3u#1]
Hey, great work on doing this, let me know you are done, this fully works and you host it somewhere, I will add it to my README

**Comment by saifshaikh1805** [comment]
Hey, I appreciate you acknowledging my efforts into this. I have made some changes, will push to the repo soon. Also, I have hosted it on firebase but I'm not sure if I should post the link on github or any public forum as it may alert Tata Sky and they might make changes to make this tool pointless. Let me know your thoughts!

**Comment by ForceGT** [comment]
Yes you are right, don't make the hosted stuff public but I can definitely link your repo once you're done if in case anyone wants to check for reference

**Comment by saifshaikh1805** [comment]
Hey, it's complete now. I have pushed all the changes to the repo.

**Comment by Mannu-1** [comment]
How to use this..

**Comment by saifshaikh1805** [comment]
@Mannu-1 you need to install node js and git CLI and then just following the instructions provided in the readme

**Comment by Mannu-1** [comment]
![Screenshot_2021-10-04-15-56-26-530_com termux](https://user-images.githubusercontent.com/90518979/135835744-50069b34-2dd1-407a-876f-9b7e5d0c0ae4.jpg)
I am getting this error while installing npm

**Comment by ssk30711** [comment]
DRM session exception is coming am i doing it wrongly or tatasky blocked it
