### ISSUE TITLE
all channels not generated

### ISSUE THREAD

**Issue by baadshah0786** [saifshaikh1805/tata-sky-m3u#12]
dear bro this method all channels not generated but when i use Techiesneh tata play web app then all channels generated

plaz see the matter and try to solve

**Comment by SalMaster007** [comment]
> dear bro this method all channels not generated but when i use Techiesneh tata play web app then all channels generated
> 
> plaz see the matter and try to solve

this is done to avoid piracy.

**Comment by vishu002** [comment]
Hello sir channel is very less in your script try to this link content-detail/pub/api/v2/channels/{id}
