### ISSUE TITLE
Error 414 on OTT Nav

### ISSUE THREAD

**Issue by kripamoymargram** [saifshaikh1805/tata-sky-m3u#15]
Fetching channels but getting error 414 on OTT nav while playing m3u.
For other apps, it's just black screen.

**Comment by saifshaikh1805** [comment]
Sorry, I am not able to replicate the issue at my end.

**Comment by kripamoymargram** [comment]
Apparently 414 means long URI (found googling) and the license key generated by this script is 6 or 7 times longer than [similar scripts](https://github.com/Shra1V32/TataSky-Playlist-AutoUpdater) by other developers. Can it be made smaller working license key? 
Thank you

**Comment by saifshaikh1805** [comment]
Fixed
