### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by drtiwarir** [saifshaikh1805/tata-sky-m3u#18]
I deployed it using Vercel, but the link did not work, have I done anything wrong ?
Please help

Thanks

**Comment by saifshaikh1805** [comment]
What is the error message you're getting?

**Comment by drtiwarir** [comment]
Thanks for your reply
When I worked on vercel I got a link, https://bit.lyxxxdd
(this is not the original link but the format)
I pasted this link in Tivimate ( tried in OTT navigator also)
But kept getting error
Please advise how should I proceed?

Thanks
Ravi

**Comment by saifshaikh1805** [comment]
What do you see when you open this link in the browser?

**Comment by drtiwarir** [comment]
I have fixed it, working great 

Thanks

**Comment by saifshaikh1805** [comment]
Cool.. Please star the repo if it's helpful to you.

**Comment by drtiwarir** [comment]
I don’t want to star
But happy to support you guys
How can I do ?
But don’t forget the boss botallen

Thanks

**Comment by drtiwarir** [comment]
I can definitely buy a coffee
