### ISSUE TITLE
ALL CHANNELS NOT SHOW IN M3U

### ISSUE THREAD

**Issue by vgshah1994** [saifshaikh1805/tata-sky-m3u#19]
ALL CHANNELS NOT SHOW IN M3U

**Comment by SalMaster007** [comment]
you will get only those channels which had subscribed.

**Comment by vgshah1994** [comment]
> you will get only those channels which had you subscribed.

YES BUT ALL SUBSCRIBED CHANNELS ARE NOT SHOWING AND SOME OF SHOWED ALSO NOT WORKING IN CREATED M3U

**Comment by SalMaster007** [comment]
Use this script
[TataSky-Playlist-AutoUpdater](https://github.com/Shra1V32/TataSky-Playlist-AutoUpdater)

**Comment by vgshah1994** [comment]
> Use this script [TataSky-Playlist-AutoUpdater](https://github.com/Shra1V32/TataSky-Playlist-AutoUpdater)

Yes I tried this too it's work perfectly but I like your script because it's creat just one link ,We not have to change link everyday in your script.

**Comment by vgshah1994** [comment]
> > Use this script [TataSky-Playlist-AutoUpdater](https://github.com/Shra1V32/TataSky-Playlist-AutoUpdater)
> 
> Yes I tried this too it's work perfectly but I like your script because it's creat just one link ,We not have to change link everyday in your script.

Can you share your telegram id so we can discuss on script on it.

**Comment by SalMaster007** [comment]
use network stream player or Tivimate 2.1.5
you won't face any issue..

**Comment by saifshaikh1805** [comment]
> > you will get only those channels which had you subscribed.
> 
> YES BUT ALL SUBSCRIBED CHANNELS ARE NOT SHOWING AND SOME OF SHOWED ALSO NOT WORKING IN CREATED M3U



> ALL CHANNELS NOT SHOW IN M3U

Which channels are not showing?

**Comment by vgshah1994** [comment]
> > > you will get only those channels which had you subscribed.
> > 
> > 
> > YES BUT ALL SUBSCRIBED CHANNELS ARE NOT SHOWING AND SOME OF SHOWED ALSO NOT WORKING IN CREATED M3U
> 
> > ALL CHANNELS NOT SHOW IN M3U
> 
> Which channels are not showing?

In saif's script it show 251 channels and shravan's script show 277 channels. Both generated on same tata id. In saif's script star sport not working.

**Comment by saifshaikh1805** [comment]
Star channels issue was fixed in the last commit. When did you deploy?

**Comment by vgshah1994** [comment]
> Star channels issue was fixed in the last commit. When did you deploy?

On 13th November 2022.

**Comment by vgshah1994** [comment]
> Star channels issue was fixed in the last commit. When did you deploy?

Other channels working just star sport is not work.

**Comment by saifshaikh1805** [comment]
It's working for everybody else. Make sure you have subscribed to the star sports channels. Then deploy and generate the playlist again.

**Comment by vgshah1994** [comment]
> It's working for everybody else. Make sure you have subscribed to the star sports channels. Then deploy and generate the playlist again.

I have subscribed star sport and it's working in shravan's script.

**Comment by vgshah1994** [comment]
> It's working for everybody else. Make sure you have subscribed to the star sports channels. Then deploy and generate the playlist again.

Getting error " 404 stream not reachable, contact your provider "

**Comment by saifshaikh1805** [comment]
I think Shravan's script gives Star channels even if you have not subscribed to Star channels. I don't support that. I have just confirmed with some people that all the subscribed channels are working fine with my script.

**Comment by vgshah1994** [comment]
> I think Shravan's script gives Star channels even if you have not subscribed to Star channels. I don't support that. I have just confirmed with some people that all the subscribed channels are working fine with my script.

No I only get thos star channela which I have subscribed in shravan's script. And working completely fine. I like your script so  just want to share the issue which happened with me. But it's fine any other not facing it. Anyway can you just help me for where i can get link which I have generated previously.
