### ISSUE TITLE
DRM Issues

### ISSUE THREAD

**Issue by ssk30711** [saifshaikh1805/tata-sky-m3u#2]
DRM session exception comes when trying to play channels
please tell how to solve this issue

**Comment by saifshaikh1805** [comment]
I just checked. It's working fine.

**Comment by saifshaikh1805** [comment]
@ssk30711 I have made some changes. Can you deploy again and check?

**Comment by ssk30711** [comment]
Yes now it is working

**Comment by ssk30711** [comment]
Thanks
