### ISSUE TITLE
timeout error

### ISSUE THREAD

**Issue by dnyaneshpainjane** [saifshaikh1805/tata-sky-m3u#21]
![image](https://user-images.githubusercontent.com/81969659/214915435-5ea55fe9-b373-4f2c-81b3-42af4f1b6474.png)
facing this issue

**Comment by saifshaikh1805** [comment]
Did you deploy or are you using my URL?

**Comment by dnyaneshpainjane** [comment]
I have deployed on my own

**Comment by saifshaikh1805** [comment]
There must be something wrong with your deployment. Check the logs on vercel or try deploying again.
