### ISSUE TITLE
otp not submitted

### ISSUE THREAD

**Issue by anilkchugh** [saifshaikh1805/tata-sky-m3u#23]
when send otp. otp is send on mobile but error is displayed , not submitted otp & not generated playlist
it is same on our repo & same on your repo. pl. help
![IMG_20230217_122459](https://user-images.githubusercontent.com/124760322/219571675-b1c405b1-9742-4fcc-8c19-914183f1d1c0.jpg)

**Comment by saifshaikh1805** [comment]
Fixed.
