### ISSUE TITLE
After creating some error arrived 

### ISSUE THREAD

**Issue by Jadeja99** [saifshaikh1805/tata-sky-m3u#24]
Sir i cant create new m3u playlist some error shown can u help me with that 
![FBE7D865-2487-43D0-886F-E3934E483700](https://user-images.githubusercontent.com/124027978/226170663-27d4ef16-6db7-4f96-bffa-96e5b7884ce4.png)
![E824D8C5-87E4-4D6A-9E73-EEC606DB99B0](https://user-images.githubusercontent.com/124027978/226170666-d3e5ddfc-308a-4577-9f37-ed795722c2c2.png)

**Comment by saifshaikh1805** [comment]
Check runtime log in vercel and post screenshot here.
