### ISSUE TITLE
Help

### ISSUE THREAD

**Issue by tauhidkazmii** [saifshaikh1805/tata-sky-m3u#27]
I want your number brother

**Comment by baadshah0786** [comment]
Can you contact me through telegram i have a solution

**Comment by tauhidkazmii** [comment]
> Can you contact me through telegram i have a solution 

How may connect with you via telegram

**Comment by baadshah0786** [comment]
Tell me your g mail id i will contact directly

**Comment by tauhidkazmii** [comment]
> Your tata Play working all channels without all channels subscription 

My mail id is afser.kazmi@gmail.com
