### ISSUE TITLE
M3u generate problem 

### ISSUE THREAD

**Issue by rc3546886** [saifshaikh1805/tata-sky-m3u#28]
Bhai OTP daal kar m3u generate Kiya per naam ke alawa link nahi show kar kara

Or bro json channel update karo some channel not working like Star gold HD 

![Screenshot_2023-06-16-07-47-39-765-edit_com opera browser afin](https://github.com/saifshaikh1805/tata-sky-m3u/assets/73817211/b2caaad5-8ac9-43d8-abd4-5ba6e3c17cf5)

**Comment by tauhidkazmii** [comment]
Getting same error

**Comment by rc3546886** [comment]
> Getting same error

Bro ye playlist validity kitni hoti hai

**Comment by rc3546886** [comment]
Solve the issue fast please

**Comment by tauhidkazmii** [comment]
Same issue bro

**Comment by saifshaikh1805** [comment]
fixed
