### ISSUE TITLE
M3u generate issue 

### ISSUE THREAD

**Issue by rc3546886** [saifshaikh1805/tata-sky-m3u#29]
M3u url not showing 
![Screenshot_2023-06-16-13-49-10-197-edit_com opera browser afin](https://github.com/saifshaikh1805/tata-sky-m3u/assets/73817211/c2d3601d-c7f6-4784-bc99-b25eb69bfe38)

**Comment by tauhidkazmii** [comment]
Please fix the bug

**Comment by rc3546886** [comment]
Screen shot send bro

**Comment by rc3546886** [comment]
> Bro please help me ☹️

Send your issue here

**Comment by saifshaikh1805** [comment]
fixed
