### ISSUE TITLE
host

### ISSUE THREAD

**Issue by SalMaster007** [saifshaikh1805/tata-sky-m3u#3]
will you please explain how to host this files on firebase?

**Comment by saifshaikh1805** [comment]
You can also host it on vercel. Just fork the repo, go to vercel, then import and deploy. Before deploying, vercel will give you an option to add environment variables. Add the following env variable:
`REACT_APP_M3U_FUNCTION_BASE_URL = <THE DOMAIN YOU COPIED IN STEP 2. PUT IT HERE DOUBLE QUOTES>
`

**Comment by ssk30711** [comment]
Hosted on Netlify & it is working fine
