### ISSUE TITLE
Now URL Generated

### ISSUE THREAD

**Issue by Mobassar4u** [saifshaikh1805/tata-sky-m3u#32]
Only Show  Dynamic URL to get m3u:

You can use the above m3u URL in OTT Navigator or Tivimate app to watch all your subscribed channels.

The generated m3u URL is for permanent use and is not required to be refreshed every 24 hours. Enjoy!

No dynamic url show plz fix it early if possible thnks

**Comment by saifshaikh1805** [comment]
fixed
