### ISSUE TITLE
Playlist not working

### ISSUE THREAD

**Issue by Rajveer-Mahida** [saifshaikh1805/tata-sky-m3u#4]
Hey bro, the playlist is generating, but it is not working. Would you please check that

**Comment by saifshaikh1805** [comment]
I just checked. It's working fine

**Comment by Rajveer-Mahida** [comment]
I am sharing link you in tg check that

**Comment by saifshaikh1805** [comment]
@Rajveer-Mahida I have made some changes. Can you deploy again and check?

**Comment by Rajveer-Mahida** [comment]
It's still not working.

**Comment by saifshaikh1805** [comment]
I have checked with others and it's working fine. Hence, closing the issue.
