### ISSUE TITLE
Request : Stalker Portal 

### ISSUE THREAD

**Issue by Fakeabhijit** [saifshaikh1805/tata-sky-m3u#9]
Is there any way to generate Stalker Portal link with Mac address.
Stalker Portal are more stable

**Comment by HuskyHunk** [comment]
https://sinister.ly/Thread-Convert-MAC-to-M3U


This might help you,

Note : if the server supports you can create a m3u , or else you cannot , also 1 important , if you create a m3u with mac , password for mac playlists are dynamic and they change frequently , so it's no use of creating m3u with mac codes

**Comment by saifshaikh1805** [comment]
> Is there any way to generate Stalker Portal link with Mac address. Stalker Portal are more stable

Hello.. My knowledge on stalker portal is very limited. You will have to explain me what it is. If it's something that I find interesting then I'll definitely look into it.

**Comment by saifshaikh1805** [comment]
Closing.
